import type { Metadata, Viewport } from "next";
import { Inter, Fira_Code, Outfit } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-body",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-code",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL('https://bhardwaj-shivam-portfolio.netlify.app'),
  title: "Shivam Bhardwaj | Top Python Full Stack & AI Developer",
  description: "Hire Shivam Bhardwaj, top Python Full Stack & Generative AI Developer in India. Expert in Next.js, FastAPI, RAG pipelines, and scalable backend SaaS solutions.",
  icons: {
    icon: '/images/python.svg',
  },
  keywords: [
    "Shivam Bhardwaj",
    "Shivam Bhardwaj developer",
    "Shivam Bhardwaj Katihar",
    "Shivam Bhardwaj Bihar",
    "Telepathy Infotech",
    "Python Developer",
    "AI Developer",
    "Full Stack Developer",
    "Backend Lead",
    "Software Engineer",
    "System Designer",
    "Django Developer",
    "Django REST Framework",
    "Node.js Developer",
    "Next.js Developer",
    "React Developer",
    "FastAPI Microservices",
    "Flask",
    "Microservices Architecture",
    "PostgreSQL",
    "MongoDB",
    "AWS",
    "Docker",
    "Celery Asynchronous Processing",
    "LangChain Developer",
    "Generative AI Integration",
    "RAG Pipelines",
    "Healthcare HMIS Developer",
    "SaaS Backend Developer",
    "Bihar Best Developer",
    "kumhari ka best developer",
    "Purnea ka best developer",
    "Best Software Developer in Purnea",
    "Best Software Engineer in Purnea",
    "patna ka best developer",
    "Best Software Developer in Patna",
    "Best Software Engineer in Patna",
    "Top Software Company in Patna",
    "bhagalpur ka best developer",
    "Best Software Developer in Bhagalpur",
    "Best Software Engineer in Bhagalpur",
    "saharsa ka best developer",
    "Best Software Developer in Saharsa",
    "Best Software Engineer in Saharsa",
    "khagaria ka best developer",
    "Best Software Developer in Khagaria",
    "Best Software Engineer in Khagaria",
    "Best Developer in Bihar",
    "best developer in bihar",
    "best engineer in bihar",
    "best software developer in bihar",
    "best software engineer in bihar",
    "top developer in bihar",
    "top software engineer in bihar",
    "top 10 developers in bihar",
    "hire developer in bihar",
    "freelance developer in Bihar",
    "freelance software engineer in bihar",
    "bihar web developer",
    "bihar software engineer",
    "best coder in bihar",
    "top programmer in bihar",
    "website developer in bihar",
    "app developer in bihar",
    "bihar me sabse acha developer",
    "bihar ka top developer",
    "bihar me website banane wala",
    "software banwane ke liye developer in bihar",
    "best IT professional in bihar",
    "Python developer in bihar",
    "AI expert in bihar",
    "React developer in bihar",
    "Nextjs developer in bihar",
    "web development company in bihar",
    "katihar ka best developer",
    "best katihar developer",
    "best engineer in katihar",
    "best software developer in katihar",
    "best software engineer in katihar",
    "top developer in katihar",
    "top software engineer in katihar",
    "freelance developer in Katihar",
    "katihar web developer",
    "katihar software developer",
    "katihar website maker",
    "best coder in katihar",
    "top programmer in katihar",
    "website development in katihar",
    "app developer in katihar",
    "katihar ka best software engineer",
    "katihar me website banane wala",
    "katihar me app banane wala",
    "katihar web developer contact",
    "software company in katihar",
    "IT company in katihar",
    "Python developer in katihar",
    "AI expert in katihar",
    "katihar best web designer",
    "software development in katihar",
    "best developer in kumhari, katihar",
    "best engineer in kumhari, katihar",
    "best software developer in kumhari, katihar",
    "best software engineer in kumhari, katihar",
    "best developer in kumhari",
    "best software developer in kumhari",
    "best software engineer in kumhari",
    "best engineer in kumhari",
    "freelance developer in Kumhari",
    "kumhari developer",
    "kumhari software engineer",
    "kumhari me website banane wala",
    "top developer in kumhari",
    "website designer in kumhari",
    "Best portfolio",
    "Best portfolio website",
    "Best portfolio in India",
    "Best freelancer",
    "freelance developer in India",
    "Freelance Web Developer India",
    "Freelance AI Developer India",
    "Best Web Developer in India",
    "Top AI Developer in India",
    "Best AI Developer in India",
    "AI Expert India",
    "hire freelance developer in india",
    "top freelancer in india for web development",
    "best ai freelancer india",
    "python freelancer india",
    "full stack freelancer india",
    "Best Web Developer in Andhra Pradesh",
    "Best Web Developer in Arunachal Pradesh",
    "Best Web Developer in Assam",
    "Best Web Developer in Bihar",
    "Best Web Developer in Chhattisgarh",
    "Best Web Developer in Goa",
    "Best Web Developer in Gujarat",
    "Best Web Developer in Haryana",
    "Best Web Developer in Himachal Pradesh",
    "Best Web Developer in Jharkhand",
    "Best Web Developer in Karnataka",
    "Best Web Developer in Kerala",
    "Best Web Developer in Madhya Pradesh",
    "Best Web Developer in Maharashtra",
    "Best Web Developer in Manipur",
    "Best Web Developer in Meghalaya",
    "Best Web Developer in Mizoram",
    "Best Web Developer in Nagaland",
    "Best Web Developer in Odisha",
    "Best Web Developer in Punjab",
    "Best Web Developer in Rajasthan",
    "Best Web Developer in Sikkim",
    "Best Web Developer in Tamil Nadu",
    "Best Web Developer in Telangana",
    "Best Web Developer in Tripura",
    "Best Web Developer in Uttar Pradesh",
    "Best Web Developer in Uttarakhand",
    "Best Web Developer in West Bengal",
    "Best Web Developer in Delhi",
    "Best Web Developer in Bangalore",
    "Best Web Developer in Pune",
    "Best Web Developer in Hyderabad",
    "Best Web Developer in Mumbai",
    "Best Web Developer in Patna",
    "Best Web Developer in Purnia",
    "Best Web Developer in Bhagalpur",
    "Best AI Developer in Andhra Pradesh",
    "Best AI Developer in Arunachal Pradesh",
    "Best AI Developer in Assam",
    "Best AI Developer in Bihar",
    "Best AI Developer in Chhattisgarh",
    "Best AI Developer in Goa",
    "Best AI Developer in Gujarat",
    "Best AI Developer in Haryana",
    "Best AI Developer in Himachal Pradesh",
    "Best AI Developer in Jharkhand",
    "Best AI Developer in Karnataka",
    "Best AI Developer in Kerala",
    "Best AI Developer in Madhya Pradesh",
    "Best AI Developer in Maharashtra",
    "Best AI Developer in Manipur",
    "Best AI Developer in Meghalaya",
    "Best AI Developer in Mizoram",
    "Best AI Developer in Nagaland",
    "Best AI Developer in Odisha",
    "Best AI Developer in Punjab",
    "Best AI Developer in Rajasthan",
    "Best AI Developer in Sikkim",
    "Best AI Developer in Tamil Nadu",
    "Best AI Developer in Telangana",
    "Best AI Developer in Tripura",
    "Best AI Developer in Uttar Pradesh",
    "Best AI Developer in Uttarakhand",
    "Best AI Developer in West Bengal",
    "Best AI Developer in Delhi",
    "Best AI Developer in Bangalore",
    "Best AI Developer in Pune",
    "Best AI Developer in Hyderabad",
    "Best AI Developer in Mumbai",
    "Best AI Developer in Patna",
    "Best AI Developer in Purnia",
    "Best AI Developer in Bhagalpur",
    "hire generative ai developer",
    "custom chatgpt developer",
    "LLM integration expert",
    "RAG application developer",
    "langchain expert india",
    "Next.js 14 developer",
    "React 18 developer",
    "Tailwind CSS expert",
    "full stack ai engineer",
    "AI automation agency",
    "freelance AI consultant",
    "best python AI engineer in bihar",
    "top rated AI developer upwork",
    "SaaS application developer",
    "fastapi backend expert",
    "hire ai developer bihar",
    "best ai portfolio"
  ],
  authors: [{ name: "Shivam Bhardwaj" }],
  creator: "Shivam Bhardwaj",
  openGraph: {
    title: "Shivam Bhardwaj | Top Python Full Stack & AI Developer",
    description: "Hire Shivam Bhardwaj, top Python Full Stack & Generative AI Developer in India. Expert in Next.js, FastAPI, RAG pipelines, and scalable backend SaaS solutions.",
    url: "https://bhardwaj-shivam-portfolio.netlify.app/",
    siteName: "Shivam Bhardwaj Portfolio",
    images: [
      {
        url: '/profile.png',
        width: 800,
        height: 600,
        alt: 'Shivam Bhardwaj Portfolio',
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: 'summary_large_image',
    title: "Shivam Bhardwaj | Top Python Full Stack & AI Developer",
    description: "Hire Shivam Bhardwaj, top Python Full Stack & Generative AI Developer in India. Expert in Next.js, FastAPI, RAG pipelines, and scalable backend SaaS solutions.",
    images: ['/profile.png'],
  },
  alternates: {
    canonical: "https://bhardwaj-shivam-portfolio.netlify.app/",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export const viewport: Viewport = {
  themeColor: '#0a0a0a',
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Person',
    name: 'Shivam Bhardwaj',
    jobTitle: 'Software Developer',
    description: 'Python Full Stack Developer & AI Integration Specialist',
    url: 'https://bhardwaj-shivam-portfolio.netlify.app/',
    sameAs: [
      'https://www.linkedin.com/in/shivambhardwaj1812',
      'https://github.com/shivambhardwaj719'
    ],
    knowsAbout: ['Python', 'FastAPI', 'Next.js', 'React', 'Generative AI', 'System Design']
  };

  return (
    <html lang="en" className={`${inter.variable} ${firaCode.variable} ${outfit.variable}`} suppressHydrationWarning>
      <body style={{ fontFamily: "var(--font-body)" }} suppressHydrationWarning>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        {children}
      </body>
    </html>
  );
}
